codeforcescrawler/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from login import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name='index'),
    path('special/',views.special,name='special'),
    path('login/',include('login.urls')),
    path('logout/', views.user_logout, name='logout'),
    path('time-table/', views.time_table, name='time_table'),
    path('contest-stats/',views.contest_stats, name='contest_stats'),
    path('login/search-handle/',views.search_handle, name='search_handle'),
    
] 

login/urls.py
from django.conf.urls import url
from . import views
from django.urls import path

# SET THE NAMESPACE!
app_name = 'login'

# Be careful setting the name to just /login use userlogin instead!
urlpatterns=[
    url(r'^register/$',views.register,name='register'),
    url(r'^user_login/$',views.user_login,name='user_login'),
]

login/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserProfileInfo(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    cf_handle = models.CharField(max_length=35)
    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)
    
    def __str__(self):
        return self.user.username

class languages(models.Model):
    name = models.CharField(max_length = 200)
    val = models.IntegerField()

    def __str__(self):
        return self.name

class verdicts(models.Model):
    name = models.CharField(max_length = 200)
    val = models.IntegerField()

    def __str__(self):
        return self.name

class levels(models.Model):
    name = models.CharField(max_length = 200)
    val = models.IntegerField()

    def __str__(self):
        return self.name

login/forms.py
from django import forms
from .models import UserProfileInfo
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username','password','email')

class UserProfileInfoForm(forms.ModelForm):
     class Meta():
         model = UserProfileInfo
         fields = ('cf_handle','profile_pic')

class SearchHandle(forms.Form):
    cf_handle = forms.CharField(label="Search Handle", max_length=35)

login/views.py
from django.shortcuts import render
from .forms import UserForm,UserProfileInfoForm
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from . import models
from .forms import SearchHandle
from .models import languages, verdicts, levels

from bs4 import BeautifulSoup
import requests
from lxml import html

import pandas as pd
import matplotlib.pyplot as plt, mpld3


from collections import OrderedDict
from . import fusioncharts

def index(request):
    return render(request,'login/index.html')

@login_required
def special(request):
    return HttpResponse("You are logged in !")

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            if 'profile_pic' in request.FILES:
                print('found it')
                profile.profile_pic = request.FILES['profile_pic']
            profile.save()
            registered = True
        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()
    return render(request,'login/registration.html',
                          {'user_form':user_form,
                           'profile_form':profile_form,
                           'registered':registered})


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("Your account was inactive.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username,password))
            return HttpResponse("Invalid login details given")
    else:
        return render(request, 'login/login.html', {})


def time_table(request):
    fcd = fetch_time_table()
    
    return render(request, "login/time_table.html", {"cols" : fcd})


def fetch_time_table():

    url = "https://codeforces.com/contests"
    page = requests.get(url)

    bs=BeautifulSoup(page.content, 'html.parser')
    table_body = bs.find_all('table', class_="")

    cnt = 0
    for item in table_body:
        rows = item.find_all('tr')
        for row in rows:
            cols=row.find_all('td')
            cols=[x.text.strip() for x in cols]

            if len(cols) == 0:
                cnt = cnt + 1

            if cnt < 2 and len(cols)>=3:
                yield cols


def contest_stats(request):

    # OneToOne Field hai user in UserProfileInfo model to usko access karne
    # ka tareeka!!!    
    profile = request.user.userprofileinfo
    handle = profile.cf_handle

    fcs = fetch_contest_stats(handle)
    chart = {"output_languages" :  display_stats_languages(handle).render(),
            "output_verdicts" :  display_stats_verdicts(handle).render(),
            "output_levels" :  display_stats_levels(handle).render(),
    }

    fcs.update(chart)

    return render(request, 'login/contest_stats.html', fcs)

    profile = request.user.userprofileinfo
    handle = profile.cf_handle
    fcs = fetch_contest_stats(handle)

    submissionsFigure(request)

    return render(request, 'login/figure_html.html', fcs)

def submissionsFigure(request):
    profile = request.user.userprofileinfo
    handle = profile.cf_handle

    df = fetchSubmissionDetails(handle)

    lang_occurence_data = df['Lang'].value_counts()

    labels = lang_occurence_data.keys().tolist()
    sizes = lang_occurence_data.values

    fig = plt.figure()
    plt.pie(sizes, labels=labels)

    html_fig = mpld3.fig_to_html(fig)

    html_fig = "{% extends 'login/base.html' %} \n {% block body_block %} \n" + html_fig + "{% endblock %}"

    file = open('templates/login/figure_html.html', "w")
    file.write(html_fig)
    file.close()


def fetch_contest_stats(handle):
    start_url = "https://www.codeforces.com/"

    cf_handle = handle
    contests_url = start_url+'contests/with/'+cf_handle

    page = requests.get(contests_url)
    soup = BeautifulSoup(page.content, 'lxml')


    table = soup.find('table', class_='tablesorter user-contests-table')
    tbody = table.find('tbody')

    ROWS = tbody.find_all('tr')

    delta_rating = []
    rank_list = []

    for item in ROWS:
        elements = item.find_all('td')
        rank = int(elements[2].find('a').text)
        rating_change = int(elements[4].text)

        delta_rating.append(rating_change)
        rank_list.append(rank)

    delta_rating.sort()
    rank_list.sort()

    mydict = {
        'Handle' : cf_handle,
        'No_of_Contests' : ROWS[0].find('td').text,
        'Best_Rank' : rank_list[0],
        'Worst_Rank' : rank_list[len(rank_list)-1],
        'Max_Up' : delta_rating[len(delta_rating)-1],
        'Max_Down' : delta_rating[0],
    }

    return mydict

def search_handle(request):
    if request.method == "POST":
        form = SearchHandle(request.POST)


        if form.is_valid():
            handle = form.cleaned_data["cf_handle"]
            # print(handle)

            fcs = fetch_contest_stats(handle)
            chart = {"output_languages" :  display_stats_languages(handle).render(),
                    "output_verdicts" :  display_stats_verdicts(handle).render(),
                    "output_levels" :  display_stats_levels(handle).render(),
            }

            fcs.update(chart)

            return render(request, 'login/contest_stats.html', fcs)

    else :
        form = SearchHandle()
    
    form = SearchHandle()

    return render(request, 'login/search.html', {"form":form})

def get_submission_stats(handle):
    languages.objects.all().delete()
    verdicts.objects.all().delete()
    levels.objects.all().delete()

    page = requests.get("https://codeforces.com/submissions/" + handle)

    soup = BeautifulSoup(page.content, 'lxml')
    div = soup.find_all('div', class_='pagination')

    if len(div) == 1:
        t=1
    
    else:
        ul = div[1].find('ul')
        li = ul.find_all('li')

        t = int(li[-2].text)
    
    
    val = pd.Series()
    verd = pd.Series()
    lev = pd.Series()

    for i in range(t):
        p = pd.read_html("https://codeforces.com/submissions/" + handle + "/page/" + str(i+1))
        table = p[5]

        val = val.combine(table['Lang'].value_counts(),(lambda x1, x2 : x1+x2), fill_value=0)
        verd = verd.combine(table['Verdict'].value_counts(),(lambda x1, x2 : x1+x2), fill_value=0)
        lev = lev.combine(table['Problem'].value_counts(),(lambda x1, x2 : x1+x2), fill_value=0)

    labels_lang = val._index
    labels_verd = verd._index
    labels_lev = lev._index


    for l in labels_lang:
        a = languages.objects.update_or_create(name = l, val = val[l])[0]
        a.save()
    
    for l in labels_verd:
        a = verdicts.objects.update_or_create(name = l, val = verd[l])[0]
        a.save()

    for l in labels_lev:
        a = levels.objects.update_or_create(name = l, val = lev[l])[0]
        a.save()


def display_stats_languages(handle):
    get_submission_stats(handle)

    chartConfig = OrderedDict()
    chartConfig["caption"] = "Languages of " + handle
    chartConfig["xAxisName"] = "Languages"
    chartConfig["xAxisName"] = "Submissions"
    chartConfig["theme"] = "fusion"
    chartConfig["animation"] = ""

    datasource = OrderedDict()
    datasource["Chart"] = chartConfig
    datasource["data"] = []
    # print(languages.objects.all())
    for l in languages.objects.all():
        datasource["data"].append({"label": l.name, "value": str(l.val)})
    
    graph2D = fusioncharts.FusionCharts("pie2d", "Languages Chart", "600", "400", "languages_chart", "json", datasource)

    return graph2D

def display_stats_verdicts(handle):

    chartConfig = OrderedDict()
    chartConfig["caption"] = "Verdicts of " + handle
    chartConfig["xAxisName"] = "Verdicts"
    chartConfig["xAxisName"] = "Submissions"
    chartConfig["theme"] = "fusion"
    chartConfig["animation"] = ""

    datasource = OrderedDict()
    datasource["Chart"] = chartConfig
    datasource["data"] = []

    WA = 0
    AC = 0
    RTE = 0
    MLE = 0
    CE = 0
    TLE = 0

    for l in verdicts.objects.all():
        item = l.name
        if item[:5] == "Wrong":
            WA += l.val
        
        elif item[:5] == "Time":
            TLE += l.val

        elif item == "Accepted":
            AC += l.val

        elif item[:6] == "Memory":
            MLE += l.val

        elif item[:11] == "Compilation":
            CE += l.val

        elif item[:7] == "Runtime":
            RTE += l.val
        
    datasource["data"].append({"label": "Accepted", "value": AC})
    datasource["data"].append({"label": "Wrong Answer", "value": WA})
    datasource["data"].append({"label": "Runtime Error", "value": RTE})
    datasource["data"].append({"label": "Memory Limit Exceeded", "value": MLE})
    datasource["data"].append({"label": "Compilation Error", "value": CE})
    datasource["data"].append({"label": "Time Limit Exceeded", "value": TLE})
    
    graph2D = fusioncharts.FusionCharts("pie2d", "Verdicts Chart", "700", "500", "verdicts_chart", "json", datasource)

    return graph2D

def display_stats_levels(handle):

templates/login/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title> {% block title %}  {% endblock %} </title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous"> -->
    
    {% load static %}
      <script type="text/javascript" src="{% static "fusioncharts/fusioncharts.js" %}"></script>
      <script type="text/javascript" src="{% static "fusioncharts/fusioncharts.charts.js" %}"></script>
      <script type="text/javascript" src="{% static "fusioncharts/themes/fusioncharts.theme.fusion.js" %}"></script>

  </head>
  <body>
    
    <nav class="navbar navbar-default navbar-static-top " >
      <div class="container">
        <ul class="nav navbar-nav">
          {# Django Home Link / Admin Link / Register Link#}

          <li><a class="navbar-brand" href="{% url 'index' %}">Codeforces Crawler</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>


          {% if not user.is_authenticated %}
            <li><a class="navbar-link" href="{% url 'login:register' %}">Register</a></li> 
          {% endif %}

          {% if user.is_authenticated %}
            <li><a class="navbar-link" href="{% url 'contest_stats' %}">Contest Stats</a></li>
          {% endif %}
          
          <li><a class="navbar-link" href="{% url 'time_table' %}">Time Table</a></li>  


          {# Some logic on what to display for last item#}

          {% if user.is_authenticated %}
            <li><a href="{% url 'search_handle' %}">Search Handle</a></li>
            <li><a href="{% url 'logout' %}">Logout</a></li>
          {% else %}
            <li><a class="navbar-link" href="{% url 'login:user_login' %}">Login</a></li>
          {% endif %}
</ul>
      </div>
    </nav>
    <div class="container">
    {% block body_block %}
    {% endblock %}
    </div>



  </body>
</html>

templates/login/contest_stats.html
{% extends "login/base.html" %}

{% block title %}
User-Profile
{% endblock %}

{% block body_block %}
    
    <div id="languages_chart">
        {{output_languages | safe}}
    </div>

    <div id="verdicts_chart">
        {{output_verdicts | safe}}
    </div>

    <div id="levels_chart">
        {{output_levels | safe}}
    </div>

    <div class="w-25 p-3">
        <table class="table table-striped">
        
            <thead>
                <tr class="bg-primary">
                    <th scope="col">Contest Stats </th>
                    <th scope="col">{{Handle}}</th>
                </tr>
            </thead>
    
            <tbody>
                <tr>
                    <th scope="row">
                        Best Rank 
                    </th>
    
                    <td> {{Best_Rank}} </td>
                </tr>
    
                <tr>
                    <th scope="row">
                        Worst Rank
                    </th>
    
                    <td> {{Worst_Rank}} </td>
                </tr>
    
                <tr>
                    <th scope="row">
                        Max Up
                    </th>
    
                    <td> {{Max_Up}} </td>
                </tr>
    
                <tr>
                    <th scope="row">
                        Max Down
                    </th>
    
                    <td> {{Max_Down}} </td>
                </tr>
            </tbody>
        
        </table>
    </div>


{% endblock %}

templates/login/index.html
{% extends "login/base.html" %}

{% block title %}
Home
{% endblock %}

{% block body_block %}
<div class="container">
  <div class="jumbotron">
    <h1>Welcome to the Codeforces Crawler !</h1>
    {% if user.is_authenticated %}
        <h2>Hello {{ user.username }}</h2>
    {% else %}
        <h2>Register or Login if you'd like to</h2>
    {% endif %}
  </div>
</div>
{% endblock %}

templates/login/login.html
{% extends 'login/base.html' %}

{% block title %}
Login
{% endblock %}

{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      <h1>Login here :</h1>
<form method="post" action="{% url 'login:user_login' %}">
          {% csrf_token %}
          {# A more "HTML" way of creating the login form#}
          <label for="username">Username:</label>
          <input type="text" name="username" placeholder="Username">
<label for="password">Password:</label>
          <input type="password" name="password" placeholder="Password">
<input type="submit" name="" value="Login">
</form>
</div>
  </div>
{% endblock %}

templates/login/registration.html
{% extends "login/base.html" %}
{% load static %}

{% block title %}
Registration
{% endblock %}

{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      {% if registered %}
        <h1>Thank you for registering!</h1>
      {% else %}
        <h1>Register Here</h1>
        <h3>Just fill out the form.</h3>
<form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{ user_form.as_p }}
          {{ profile_form.as_p }}
          <input type="submit" name="" value="Register">
        </form>
        
      {% endif %}
    </div>
  </div>
{% endblock %}

templates/login/search.html
{% extends "login/base.html" %}

{% block title %}
Search-Handle
{% endblock %}

{% block body_block %}

    <form method="post" action="/login/search-handle/">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit", name="save">Submit</button>
        
    </form>

{% endblock %}

templates/login/time_table.html
{% extends "login/base.html" %}

{% block title %}
Time-Table
{% endblock %}

{% block body_block %}
<h1>Time Table</h1>

<h4>Contest Details : </h4>

{% for item in cols %}
        <br /><br />
        
        <h6>Name : {{item.0}}</h6>
        <h6>Writers : {{item.1}}</h6>
        <h6>Start : {{item.2}}</h6>
        <h6>Duration : {{item.3}}</h6>
        <h6>{{item.4}}</h6>
    {% endfor %}


{% endblock %}